# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'  # You can set your required iOS version

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'            # Firebase Core
  pod 'Firebase/Analytics'       # Firebase Analytics
  pod 'Firebase/RemoteConfig'    # Firebase Remote Config

  # Optional: Other dependencies (e.g., Firebase Crashlytics, Firestore)
  # pod 'Firebase/Crashlytics'
  # pod 'Firebase/Firestore'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
